import json
d=json.load(open('import_data.json'))
P=d['projects']; V=d['variations']
pm_names={'BASIM','AKASH','DIPAK','RICHARD','JC','AFTAB'}
designers={'JINKY','ROBIN','HAYDEE','MEGANA','ANKITA','HITESH','LOUIE','CATH','PREM','ALYSSA','ARUN','SHANINA'}
def q(v): return 'null' if v in (None,'') else "'"+str(v).replace("'","''")+"'"
out=["-- seed from CONCEPT_5-_PROJECT_2026.xlsx (generated by make_seed.py)"]
out+=[f"insert into people(name,role) values ({q(n)},'PM') on conflict do nothing;" for n in sorted(pm_names)]
out+=[f"insert into people(name,role) values ({q(n)},'DESIGNER') on conflict do nothing;" for n in sorted(designers)]
contractors=sorted({p['contractor'] for p in P if p['contractor']})
out+=[f"insert into contractors(name) values ({q(c)}) on conflict do nothing;" for c in contractors]
out.append("alter table projects disable trigger trg_project_status;")
for p in P:
    st=p['status'].replace(' ','_')
    out.append(f"""insert into projects(enquiry_no,name,client,contractor_id,pm_id,pm2_id,designer_id,status,received_date,start_date,target_date,completed_date,signed_quote,excel_row)
values ({q(p['enquiry_no'])},{q(p['name'])},{q(p['client'])},(select id from contractors where name={q(p['contractor'])}),(select id from people where name={q(p['pm'])}),(select id from people where name={q(p['pm_second'])}),(select id from people where name={q(p['designer'])}),'{st}',{q(p['received_date'])},{q(p['start_date'])},{q(p['target_date'])},{q(p['completed_date'])},{p['signed_quote']},{p['excel_row']});""")
out.append("alter table projects enable trigger trg_project_status;")
out.append("insert into status_history(project_id,to_status,changed_at,note) select id,status,coalesce(start_date,received_date,current_date),'imported from Excel' from projects;")
for v in V:
    out.append(f"insert into variations(project_id,vo_no,value) values ((select id from projects where excel_row={next(p['excel_row'] for p in P if p['name']==v['project_name'])}),{v['vo_no']},{v['value']});")
open('../db/002_seed.sql','w').write('\n'.join(out)+'\n')
print(len(out),'statements')
