set search_path = scheduler, public;
-- seed from CONCEPT_5-_PROJECT_2026.xlsx (generated by make_seed.py)
insert into people(name,role) values ('AFTAB','PM') on conflict do nothing;
insert into people(name,role) values ('AKASH','PM') on conflict do nothing;
insert into people(name,role) values ('BASIM','PM') on conflict do nothing;
insert into people(name,role) values ('DIPAK','PM') on conflict do nothing;
insert into people(name,role) values ('JC','PM') on conflict do nothing;
insert into people(name,role) values ('RICHARD','PM') on conflict do nothing;
insert into people(name,role) values ('ALYSSA','DESIGNER') on conflict do nothing;
insert into people(name,role) values ('ANKITA','DESIGNER') on conflict do nothing;
insert into people(name,role) values ('ARUN','DESIGNER') on conflict do nothing;
insert into people(name,role) values ('CATH','DESIGNER') on conflict do nothing;
insert into people(name,role) values ('HAYDEE','DESIGNER') on conflict do nothing;
insert into people(name,role) values ('HITESH','DESIGNER') on conflict do nothing;
insert into people(name,role) values ('JINKY','DESIGNER') on conflict do nothing;
insert into people(name,role) values ('LOUIE','DESIGNER') on conflict do nothing;
insert into people(name,role) values ('MEGANA','DESIGNER') on conflict do nothing;
insert into people(name,role) values ('PREM','DESIGNER') on conflict do nothing;
insert into people(name,role) values ('ROBIN','DESIGNER') on conflict do nothing;
insert into people(name,role) values ('SHANINA','DESIGNER') on conflict do nothing;
insert into contractors(name) values ('115') on conflict do nothing;
insert into contractors(name) values ('BOLSOVER') on conflict do nothing;
insert into contractors(name) values ('DIRECT') on conflict do nothing;
insert into contractors(name) values ('DIRECT/LA BASA') on conflict do nothing;
insert into contractors(name) values ('FBC') on conflict do nothing;
insert into contractors(name) values ('GTS') on conflict do nothing;
insert into contractors(name) values ('GTS/7E') on conflict do nothing;
insert into contractors(name) values ('MACS') on conflict do nothing;
insert into contractors(name) values ('MACS/7E') on conflict do nothing;
insert into contractors(name) values ('MACS/ELE') on conflict do nothing;
insert into contractors(name) values ('ROMARA (OLD LCI)') on conflict do nothing;
alter table projects disable trigger trg_project_status;
insert into projects(enquiry_no,name,client,contractor_id,pm_id,pm2_id,designer_id,status,received_date,start_date,target_date,completed_date,signed_quote,excel_row)
values ('2243','MEADOWS 2, STREET 12, V16','SAM & JULIA',(select id from contractors where name='MACS'),(select id from people where name='DIPAK'),(select id from people where name=null),(select id from people where name='JINKY'),'SNAGGING','2025-05-28','2025-08-11','2026-01-31',null,69142.5,16);
insert into projects(enquiry_no,name,client,contractor_id,pm_id,pm2_id,designer_id,status,received_date,start_date,target_date,completed_date,signed_quote,excel_row)
values ('2298','DUBAI HILLS, EMERALD HILLS VILLA 82','NAGA ARCHITECTS/ NEAL SAHNI',(select id from contractors where name='DIRECT'),(select id from people where name='BASIM'),(select id from people where name=null),(select id from people where name='JINKY'),'SITE_ON_HOLD','2025-09-10','2025-09-26','2025-12-06',null,175380.45,17);
insert into projects(enquiry_no,name,client,contractor_id,pm_id,pm2_id,designer_id,status,received_date,start_date,target_date,completed_date,signed_quote,excel_row)
values ('2293','PALM JUMEIRAH FROND G, V-G02','FRANKLY BUILT CONTRACTING',(select id from contractors where name='FBC'),(select id from people where name='BASIM'),(select id from people where name=null),(select id from people where name='JINKY'),'SITE_ON_HOLD','2025-09-04','2025-06-16','2026-02-28',null,1014285.71,18);
insert into projects(enquiry_no,name,client,contractor_id,pm_id,pm2_id,designer_id,status,received_date,start_date,target_date,completed_date,signed_quote,excel_row)
values ('26-024','JUMEIRAH ISLANDS CLUSTER 18 VILLA 3','FRED & ADONIA',(select id from contractors where name='MACS/7E'),(select id from people where name='BASIM'),(select id from people where name=null),(select id from people where name='MEGANA'),'DESIGN_DRAWINGS','2026-03-16','2026-09-19','2026-11-13',null,0.0,19);
insert into projects(enquiry_no,name,client,contractor_id,pm_id,pm2_id,designer_id,status,received_date,start_date,target_date,completed_date,signed_quote,excel_row)
values ('26-091','VICTORIA HEIGHTS NOVELIA VILLA 46','JERRY AND NURIA',(select id from contractors where name='GTS/7E'),(select id from people where name='RICHARD'),(select id from people where name=null),(select id from people where name='HAYDEE'),'DESIGN_DRAWINGS','2026-05-13',null,'2026-11-20',null,0.0,20);
insert into projects(enquiry_no,name,client,contractor_id,pm_id,pm2_id,designer_id,status,received_date,start_date,target_date,completed_date,signed_quote,excel_row)
values ('26-095','JUMEIRAH ISLANDS CLUSTER 28 VILLA 13','DR.JOY',(select id from contractors where name='MACS/7E'),(select id from people where name=null),(select id from people where name=null),(select id from people where name=null),'QUOTE','2026-06-16',null,'2027-01-22',null,0.0,21);
insert into projects(enquiry_no,name,client,contractor_id,pm_id,pm2_id,designer_id,status,received_date,start_date,target_date,completed_date,signed_quote,excel_row)
values ('26-063','JUMEIRAH GOLF ESTATES REDWOOD VILLA C19','ZUBAIR SETH',(select id from contractors where name='MACS/7E'),(select id from people where name='RICHARD'),(select id from people where name=null),(select id from people where name='ROBIN'),'DESIGN_DRAWINGS','2026-05-07','2026-09-01','2027-02-05',null,2186520.0,22);
insert into projects(enquiry_no,name,client,contractor_id,pm_id,pm2_id,designer_id,status,received_date,start_date,target_date,completed_date,signed_quote,excel_row)
values ('26-105','JUMEIRAH GOLF ESTATE, JOURI HILLS','DIANA',(select id from contractors where name='DIRECT'),(select id from people where name=null),(select id from people where name=null),(select id from people where name='JINKY'),'QUOTE','2026-07-03',null,null,null,0.0,23);
insert into projects(enquiry_no,name,client,contractor_id,pm_id,pm2_id,designer_id,status,received_date,start_date,target_date,completed_date,signed_quote,excel_row)
values ('26-009','TWIN VILLA, JUMEIRAH','GHOBASH',(select id from contractors where name='DIRECT'),(select id from people where name=null),(select id from people where name=null),(select id from people where name='ROBIN'),'QUOTE','2026-03-11',null,'2026-12-30',null,10000.0,24);
insert into projects(enquiry_no,name,client,contractor_id,pm_id,pm2_id,designer_id,status,received_date,start_date,target_date,completed_date,signed_quote,excel_row)
values ('2273','JUMEIRAH GOLF ESTATE, WILDFLOWER, K37','MONTROSE PROPERTIES',(select id from contractors where name='MACS'),(select id from people where name=null),(select id from people where name=null),(select id from people where name=null),'QUOTE','2025-07-15',null,null,null,0.0,25);
insert into projects(enquiry_no,name,client,contractor_id,pm_id,pm2_id,designer_id,status,received_date,start_date,target_date,completed_date,signed_quote,excel_row)
values ('2324','JUMEIRAH GOLF ESTATE, FLAMETREE RIDGE D58','MONTROSE PROPERTIES',(select id from contractors where name='MACS'),(select id from people where name='RICHARD'),(select id from people where name=null),(select id from people where name='ROBIN'),'QUOTE','2025-10-30',null,null,null,0.0,26);
insert into projects(enquiry_no,name,client,contractor_id,pm_id,pm2_id,designer_id,status,received_date,start_date,target_date,completed_date,signed_quote,excel_row)
values ('26-052','WORLD TRADE CENTER, JUMEIRAH LIVING . UNIT 2511','PEGAH / NZ PROJECT',(select id from contractors where name='DIRECT'),(select id from people where name='DIPAK'),(select id from people where name=null),(select id from people where name='HITESH'),'DESIGN_DRAWINGS','2026-04-17','2026-07-24','2026-10-20',null,277515.0,27);
insert into projects(enquiry_no,name,client,contractor_id,pm_id,pm2_id,designer_id,status,received_date,start_date,target_date,completed_date,signed_quote,excel_row)
values ('26-118','JUMEIRAH GOLF ESATES,SANCTUARY FALLS VILLA 40','IMAD & CHRIS',(select id from contractors where name='MACS'),(select id from people where name=null),(select id from people where name=null),(select id from people where name=null),'QUOTE','2026-07-29',null,null,null,0.0,28);
insert into projects(enquiry_no,name,client,contractor_id,pm_id,pm2_id,designer_id,status,received_date,start_date,target_date,completed_date,signed_quote,excel_row)
values ('26-133','JUMEIRAH GOLF ESATES,, REDWOOD VILLA C34','BANO',(select id from contractors where name='DIRECT'),(select id from people where name=null),(select id from people where name=null),(select id from people where name='MEGANA'),'QUOTE','2026-08-18',null,null,null,0.0,29);
insert into projects(enquiry_no,name,client,contractor_id,pm_id,pm2_id,designer_id,status,received_date,start_date,target_date,completed_date,signed_quote,excel_row)
values ('26-134','JUMEIRAH ISLANDS CLUSTER 09 VILLA 14','GTS- NO NAME',(select id from contractors where name='GTS'),(select id from people where name=null),(select id from people where name=null),(select id from people where name=null),'QUOTE','2026-08-19',null,null,null,0.0,30);
insert into projects(enquiry_no,name,client,contractor_id,pm_id,pm2_id,designer_id,status,received_date,start_date,target_date,completed_date,signed_quote,excel_row)
values ('2161','SOBHA HARTLAND VILLA 35-T2','AGON CAPITAL',(select id from contractors where name='MACS'),(select id from people where name='BASIM'),(select id from people where name=null),(select id from people where name='JINKY'),'PRODUCTION','2024-10-09','2025-10-16','2026-08-01',null,990373.86,31);
insert into projects(enquiry_no,name,client,contractor_id,pm_id,pm2_id,designer_id,status,received_date,start_date,target_date,completed_date,signed_quote,excel_row)
values ('2161','SOBHA HARTLAND VILLA 36-T3','AGON CAPITAL',(select id from contractors where name='MACS'),(select id from people where name='BASIM'),(select id from people where name=null),(select id from people where name='JINKY'),'PRODUCTION','2024-10-09','2025-10-16','2026-08-22',null,990373.86,32);
insert into projects(enquiry_no,name,client,contractor_id,pm_id,pm2_id,designer_id,status,received_date,start_date,target_date,completed_date,signed_quote,excel_row)
values ('2348','MEADOWS 5, ST3, V1','SANA',(select id from contractors where name='BOLSOVER'),(select id from people where name='JC'),(select id from people where name=null),(select id from people where name='HAYDEE'),'COMPLETED','2025-11-25','2026-02-02','2026-08-14','2026-09-22',691180.0,33);
insert into projects(enquiry_no,name,client,contractor_id,pm_id,pm2_id,designer_id,status,received_date,start_date,target_date,completed_date,signed_quote,excel_row)
values ('2247','AL BARRARI, JASMINE LEAF 3 VILLA 9','HARMONY',(select id from contractors where name='GTS'),(select id from people where name='AKASH'),(select id from people where name=null),(select id from people where name='JINKY'),'INSTALLATION','2025-07-25','2026-01-22','2026-08-31',null,2020000.0,34);
insert into projects(enquiry_no,name,client,contractor_id,pm_id,pm2_id,designer_id,status,received_date,start_date,target_date,completed_date,signed_quote,excel_row)
values ('26-097','MOHAMMAD BIN RASHID CITY-D1 V804','VICTORIA',(select id from contractors where name='MACS'),(select id from people where name='AKASH'),(select id from people where name=null),(select id from people where name='ROBIN'),'SNAGGING','2026-06-19','2026-07-07','2026-08-31','2026-09-11',436759.12,35);
insert into projects(enquiry_no,name,client,contractor_id,pm_id,pm2_id,designer_id,status,received_date,start_date,target_date,completed_date,signed_quote,excel_row)
values ('2161','SOBHA HARTLAND VILLA 33-T1','AGON CAPITAL',(select id from contractors where name='GTS'),(select id from people where name='BASIM'),(select id from people where name=null),(select id from people where name='JINKY'),'COMPLETED','2024-10-09','2025-10-16','2026-06-20','2026-08-25',810860.77,36);
insert into projects(enquiry_no,name,client,contractor_id,pm_id,pm2_id,designer_id,status,received_date,start_date,target_date,completed_date,signed_quote,excel_row)
values ('2228','MEADOWS 2, ST 9, V15','MARIAM & MUBASHIR',(select id from contractors where name='115'),(select id from people where name='DIPAK'),(select id from people where name=null),(select id from people where name='ROBIN'),'INSTALLATION','2026-01-10','2026-01-21','2026-06-30',null,1150000.0,37);
insert into projects(enquiry_no,name,client,contractor_id,pm_id,pm2_id,designer_id,status,received_date,start_date,target_date,completed_date,signed_quote,excel_row)
values ('2161','SOBHA HARTLAND VILLA 34-T1','AGON CAPITAL',(select id from contractors where name='GTS'),(select id from people where name='BASIM'),(select id from people where name=null),(select id from people where name='JINKY'),'COMPLETED','2024-10-09','2025-10-16','2026-07-04','2026-08-25',810860.77,38);
insert into projects(enquiry_no,name,client,contractor_id,pm_id,pm2_id,designer_id,status,received_date,start_date,target_date,completed_date,signed_quote,excel_row)
values ('2252','JUMEIRAH GOLF ESTATE, WILDFLOWER, K36','MONTROSE PROPERTIES',(select id from contractors where name='MACS'),(select id from people where name='RICHARD'),(select id from people where name=null),(select id from people where name='ROBIN'),'SNAGGING','2025-06-18','2026-01-23','2026-07-18','2026-08-31',41370.0,39);
insert into projects(enquiry_no,name,client,contractor_id,pm_id,pm2_id,designer_id,status,received_date,start_date,target_date,completed_date,signed_quote,excel_row)
values ('26-021','VICTORY HEIGHTS ESTELLA V12','ASIM & ELAINE',(select id from contractors where name='GTS'),(select id from people where name='RICHARD'),(select id from people where name=null),(select id from people where name='HAYDEE'),'INSTALLATION','2026-02-27','2026-03-24','2026-08-15','2026-09-22',975618.0,40);
insert into projects(enquiry_no,name,client,contractor_id,pm_id,pm2_id,designer_id,status,received_date,start_date,target_date,completed_date,signed_quote,excel_row)
values ('2187','PALM JUMEIRAH VILLA A-06','PNV/ DELYAN',(select id from contractors where name='MACS'),(select id from people where name='JC'),(select id from people where name=null),(select id from people where name='ROBIN'),'INSTALLATION','2025-01-08','2025-11-17','2026-08-15',null,1530375.0,41);
insert into projects(enquiry_no,name,client,contractor_id,pm_id,pm2_id,designer_id,status,received_date,start_date,target_date,completed_date,signed_quote,excel_row)
values ('2336','GOLDEN MILE 3 PENTHOUSE 3707 PAL JUMEIRAH','LINDSEY RACHEL',(select id from contractors where name='DIRECT'),(select id from people where name='DIPAK'),(select id from people where name=null),(select id from people where name='LOUIE'),'COMPLETED','2025-11-07','2026-01-09','2026-08-28','2026-08-07',114000.0,42);
insert into projects(enquiry_no,name,client,contractor_id,pm_id,pm2_id,designer_id,status,received_date,start_date,target_date,completed_date,signed_quote,excel_row)
values ('26-002','DUBAI HILLS SIDRA 3 V120','MICHELLE PURSEY',(select id from contractors where name='DIRECT'),(select id from people where name='AKASH'),(select id from people where name=null),(select id from people where name='ANKITA'),'COMPLETED','2026-01-30','2026-03-18','2026-10-02','2026-10-02',203495.34,43);
insert into projects(enquiry_no,name,client,contractor_id,pm_id,pm2_id,designer_id,status,received_date,start_date,target_date,completed_date,signed_quote,excel_row)
values ('2271','ARABIAN RANCHES, SAHEEL1 ST 3 VILLA 5','UFUK',(select id from contractors where name='DIRECT'),(select id from people where name='AKASH'),(select id from people where name=null),(select id from people where name='CATH'),'INSTALLATION','2025-10-13','2026-05-21','2026-08-08',null,104475.0,44);
insert into projects(enquiry_no,name,client,contractor_id,pm_id,pm2_id,designer_id,status,received_date,start_date,target_date,completed_date,signed_quote,excel_row)
values ('2161','SOBHA HARTLAND VILLA 42-T1','AGON CAPITAL',(select id from contractors where name='GTS'),(select id from people where name='BASIM'),(select id from people where name=null),(select id from people where name='JINKY'),'DESIGN_DRAWINGS','2024-10-09','2025-10-16','2026-08-15',null,810860.77,45);
insert into projects(enquiry_no,name,client,contractor_id,pm_id,pm2_id,designer_id,status,received_date,start_date,target_date,completed_date,signed_quote,excel_row)
values ('26-011','MEADOWS 05 STREET 03 V43','CLAIRE',(select id from contractors where name='MACS'),(select id from people where name='DIPAK'),(select id from people where name=null),(select id from people where name='PREM'),'PRODUCTION','2026-03-05','2026-03-23','2026-08-19',null,206640.0,46);
insert into projects(enquiry_no,name,client,contractor_id,pm_id,pm2_id,designer_id,status,received_date,start_date,target_date,completed_date,signed_quote,excel_row)
values ('26-068','JUMEIRAH PARK DISTRICT 9 VILLA 21','ATITH NAIK/ SUNRISE VALLEY LLC',(select id from contractors where name='BOLSOVER'),(select id from people where name='JC'),(select id from people where name=null),(select id from people where name='HAYDEE'),'COMPLETED','2026-05-14','2026-07-17','2026-08-31','2026-09-22',91140.0,47);
insert into projects(enquiry_no,name,client,contractor_id,pm_id,pm2_id,designer_id,status,received_date,start_date,target_date,completed_date,signed_quote,excel_row)
values ('26-059','PALM JUMEIRAH, MARINA RESIDENCE 4 APT 1306','ELIAS  & SANDRA',(select id from contractors where name='GTS'),(select id from people where name='DIPAK'),(select id from people where name=null),(select id from people where name='ANKITA'),'PRODUCTION','2026-04-04','2026-05-22','2026-09-02',null,733236.0,48);
insert into projects(enquiry_no,name,client,contractor_id,pm_id,pm2_id,designer_id,status,received_date,start_date,target_date,completed_date,signed_quote,excel_row)
values ('2161','SOBHA HARTLAND VILLA 44-T2','AGON CAPITAL',(select id from contractors where name='GTS'),(select id from people where name='BASIM'),(select id from people where name=null),(select id from people where name='JINKY'),'DESIGN_DRAWINGS','2024-10-09','2025-10-16','2026-10-03',null,990373.86,49);
insert into projects(enquiry_no,name,client,contractor_id,pm_id,pm2_id,designer_id,status,received_date,start_date,target_date,completed_date,signed_quote,excel_row)
values ('2161','SOBHA HARTLAND VILLA 37-T1','AGON CAPITAL',(select id from contractors where name='GTS'),(select id from people where name='BASIM'),(select id from people where name=null),(select id from people where name='JINKY'),'DESIGN_DRAWINGS','2024-10-09','2025-10-16','2026-09-19',null,810860.77,50);
insert into projects(enquiry_no,name,client,contractor_id,pm_id,pm2_id,designer_id,status,received_date,start_date,target_date,completed_date,signed_quote,excel_row)
values ('2161','SOBHA HARTLAND VILLA 43-T3','AGON CAPITAL',(select id from contractors where name='GTS'),(select id from people where name='BASIM'),(select id from people where name=null),(select id from people where name='JINKY'),'DESIGN_DRAWINGS','2024-10-09','2025-10-16','2026-10-17',null,990373.86,51);
insert into projects(enquiry_no,name,client,contractor_id,pm_id,pm2_id,designer_id,status,received_date,start_date,target_date,completed_date,signed_quote,excel_row)
values ('26-001','JUMEIRAH ISLANDS , THE MANSIONS V15','NAEEM',(select id from contractors where name='GTS'),(select id from people where name='RICHARD'),(select id from people where name=null),(select id from people where name='ANKITA'),'PRODUCTION','2026-02-09','2026-05-22','2026-10-31',null,570486.0,52);
insert into projects(enquiry_no,name,client,contractor_id,pm_id,pm2_id,designer_id,status,received_date,start_date,target_date,completed_date,signed_quote,excel_row)
values ('26-038','ONE ZABEEL, THE RESIDENCES, APT 5004','SALEH/
ROMARA RENOVATIONS',(select id from contractors where name='ROMARA (OLD LCI)'),(select id from people where name='BASIM'),(select id from people where name=null),(select id from people where name='MEGANA'),'DESIGN_DRAWINGS','2026-03-20','2026-05-08','2026-09-30',null,948064.48,53);
insert into projects(enquiry_no,name,client,contractor_id,pm_id,pm2_id,designer_id,status,received_date,start_date,target_date,completed_date,signed_quote,excel_row)
values ('2161','SOBHA HARTLAND VILLA 41-T1','AGON CAPITAL',(select id from contractors where name='GTS'),(select id from people where name='BASIM'),(select id from people where name=null),(select id from people where name='JINKY'),'DESIGN_DRAWINGS','2024-10-09','2025-10-16','2026-10-10',null,810860.77,54);
insert into projects(enquiry_no,name,client,contractor_id,pm_id,pm2_id,designer_id,status,received_date,start_date,target_date,completed_date,signed_quote,excel_row)
values ('2161','SOBHA HARTLAND VILLA 40-T2','AGON CAPITAL',(select id from contractors where name='GTS'),(select id from people where name='BASIM'),(select id from people where name=null),(select id from people where name='JINKY'),'DESIGN_DRAWINGS','2024-10-09','2025-10-16','2026-10-24',null,990373.86,55);
insert into projects(enquiry_no,name,client,contractor_id,pm_id,pm2_id,designer_id,status,received_date,start_date,target_date,completed_date,signed_quote,excel_row)
values ('26-109','TEMPO- PADEL & WELLNESS CLUB AL QUOZ DXB','GABRIELLA/ ADAM',(select id from contractors where name='DIRECT/LA BASA'),(select id from people where name='BASIM'),(select id from people where name='AKASH'),(select id from people where name='HAYDEE'),'DESIGN_DRAWINGS','2025-12-10','2026-07-25','2026-10-30',null,973035.0,56);
insert into projects(enquiry_no,name,client,contractor_id,pm_id,pm2_id,designer_id,status,received_date,start_date,target_date,completed_date,signed_quote,excel_row)
values ('2161','SOBHA HARTLAND VILLA 39-T3','AGON CAPITAL',(select id from contractors where name='GTS'),(select id from people where name='BASIM'),(select id from people where name=null),(select id from people where name='JINKY'),'DESIGN_DRAWINGS','2024-10-09','2025-10-16','2026-11-07',null,990373.86,57);
insert into projects(enquiry_no,name,client,contractor_id,pm_id,pm2_id,designer_id,status,received_date,start_date,target_date,completed_date,signed_quote,excel_row)
values ('26-051','JUMEIRAH PARK C35 D6','DINA',(select id from contractors where name='MACS'),(select id from people where name='JC'),(select id from people where name=null),(select id from people where name='MEGANA'),'DESIGN_DRAWINGS','2026-04-17','2026-06-30','2026-11-09',null,639135.0,58);
insert into projects(enquiry_no,name,client,contractor_id,pm_id,pm2_id,designer_id,status,received_date,start_date,target_date,completed_date,signed_quote,excel_row)
values ('26-041','AL BARARI, LUNARIA, V-27','MARK',(select id from contractors where name='GTS'),(select id from people where name='AKASH'),(select id from people where name=null),(select id from people where name='MEGANA'),'DESIGN_DRAWINGS','2026-03-30','2026-05-21','2026-11-16',null,1278319.88,59);
insert into projects(enquiry_no,name,client,contractor_id,pm_id,pm2_id,designer_id,status,received_date,start_date,target_date,completed_date,signed_quote,excel_row)
values ('26-045','MIRADOR, STREET 1 VILLA 14','STUART & DEMI',(select id from contractors where name='GTS'),(select id from people where name='AKASH'),(select id from people where name=null),(select id from people where name='ROBIN'),'DESIGN_DRAWINGS','2026-04-13','2026-05-08','2026-11-17',null,678120.14,60);
insert into projects(enquiry_no,name,client,contractor_id,pm_id,pm2_id,designer_id,status,received_date,start_date,target_date,completed_date,signed_quote,excel_row)
values ('2161','SOBHA HARTLAND VILLA 38-T1','AGON CAPITAL',(select id from contractors where name='GTS'),(select id from people where name='BASIM'),(select id from people where name=null),(select id from people where name='JINKY'),'DESIGN_DRAWINGS','2024-10-09','2025-10-16','2026-11-21',null,810860.77,61);
insert into projects(enquiry_no,name,client,contractor_id,pm_id,pm2_id,designer_id,status,received_date,start_date,target_date,completed_date,signed_quote,excel_row)
values ('26-093','DUBAI HILLS, VILLA 78','SIDHANT KOTHARI / ELE INTERIORS',(select id from contractors where name='MACS/ELE'),(select id from people where name='JC'),(select id from people where name=null),(select id from people where name='ANKITA'),'DESIGN_DRAWINGS','2026-06-19','2026-07-11','2026-11-07',null,1486330.65,62);
insert into projects(enquiry_no,name,client,contractor_id,pm_id,pm2_id,designer_id,status,received_date,start_date,target_date,completed_date,signed_quote,excel_row)
values ('2356','SOBHA RESERVE V622','ISSIAR DIA',(select id from contractors where name='DIRECT'),(select id from people where name='AKASH'),(select id from people where name=null),(select id from people where name='ANKITA'),'DESIGN_DRAWINGS','2026-01-22','2026-02-20',null,null,1032465.0,63);
insert into projects(enquiry_no,name,client,contractor_id,pm_id,pm2_id,designer_id,status,received_date,start_date,target_date,completed_date,signed_quote,excel_row)
values ('2291','MEADOWS 09 STREET 11 VILLA 11','RICHARD',(select id from contractors where name='DIRECT'),(select id from people where name='DIPAK'),(select id from people where name=null),(select id from people where name='HITESH'),'DESIGN_DRAWINGS','2025-08-28','2026-04-20',null,null,60690.0,64);
insert into projects(enquiry_no,name,client,contractor_id,pm_id,pm2_id,designer_id,status,received_date,start_date,target_date,completed_date,signed_quote,excel_row)
values ('26-117','JUMEIRAH ISLANDS CLUSTER 43 VILLA 06','YOLANDA',(select id from contractors where name='GTS'),(select id from people where name='AFTAB'),(select id from people where name=null),(select id from people where name='HITESH'),'DESIGN_DRAWINGS','2026-07-22','2026-07-24','2026-09-18',null,73920.0,65);
insert into projects(enquiry_no,name,client,contractor_id,pm_id,pm2_id,designer_id,status,received_date,start_date,target_date,completed_date,signed_quote,excel_row)
values ('26-114','YAS ISLAND ABU DHABI','ORO VERDE',(select id from contractors where name='BOLSOVER'),(select id from people where name='BASIM'),(select id from people where name=null),(select id from people where name='HAYDEE'),'DESIGN_DRAWINGS','2026-07-21','2026-07-30','2026-09-18',null,258930.0,66);
alter table projects enable trigger trg_project_status;
insert into status_history(project_id,to_status,changed_at,note) select id,status,coalesce(start_date,received_date,current_date),'imported from Excel' from projects;
insert into variations(project_id,vo_no,value) values ((select id from projects where excel_row=16),1,112350.0);
insert into variations(project_id,vo_no,value) values ((select id from projects where excel_row=16),2,4431.0);
insert into variations(project_id,vo_no,value) values ((select id from projects where excel_row=24),1,166950.0);
insert into variations(project_id,vo_no,value) values ((select id from projects where excel_row=24),2,107897.6);
insert into variations(project_id,vo_no,value) values ((select id from projects where excel_row=24),3,49665.0);
insert into variations(project_id,vo_no,value) values ((select id from projects where excel_row=33),1,180000.0);
insert into variations(project_id,vo_no,value) values ((select id from projects where excel_row=33),2,49311.0);
insert into variations(project_id,vo_no,value) values ((select id from projects where excel_row=34),1,380000.0);
insert into variations(project_id,vo_no,value) values ((select id from projects where excel_row=34),2,401310.0);
insert into variations(project_id,vo_no,value) values ((select id from projects where excel_row=34),3,186589.0);
insert into variations(project_id,vo_no,value) values ((select id from projects where excel_row=34),4,145041.0);
insert into variations(project_id,vo_no,value) values ((select id from projects where excel_row=35),1,24940.0);
insert into variations(project_id,vo_no,value) values ((select id from projects where excel_row=37),1,1890.0);
insert into variations(project_id,vo_no,value) values ((select id from projects where excel_row=37),2,30544.5);
insert into variations(project_id,vo_no,value) values ((select id from projects where excel_row=39),1,142800.0);
insert into variations(project_id,vo_no,value) values ((select id from projects where excel_row=39),2,141750.0);
insert into variations(project_id,vo_no,value) values ((select id from projects where excel_row=39),3,367920.0);
insert into variations(project_id,vo_no,value) values ((select id from projects where excel_row=39),4,302715.0);
insert into variations(project_id,vo_no,value) values ((select id from projects where excel_row=40),1,44887.12);
insert into variations(project_id,vo_no,value) values ((select id from projects where excel_row=42),1,25305.0);
insert into variations(project_id,vo_no,value) values ((select id from projects where excel_row=42),2,3944.33);
insert into variations(project_id,vo_no,value) values ((select id from projects where excel_row=42),3,153938.4);
insert into variations(project_id,vo_no,value) values ((select id from projects where excel_row=43),1,10000.0);
insert into variations(project_id,vo_no,value) values ((select id from projects where excel_row=43),2,42000.0);
insert into variations(project_id,vo_no,value) values ((select id from projects where excel_row=46),1,26040.0);
insert into variations(project_id,vo_no,value) values ((select id from projects where excel_row=46),2,219660.0);
insert into variations(project_id,vo_no,value) values ((select id from projects where excel_row=48),1,32824.01);
insert into variations(project_id,vo_no,value) values ((select id from projects where excel_row=48),2,2415.0);
insert into variations(project_id,vo_no,value) values ((select id from projects where excel_row=64),1,182280.0);
